/*
 * tn.h - token type
 * programmer - 오지은, 노윤주
 * date - 20222/04/14
 */
enum tnumber {TEOF, TERROR, TNUMBER, TIDENT, TCONST, TELSE, TIF, TINT, TRETURN, 
TVOID, TWHILE, TEQUAL, TNOTEQU, TLESSE, TGREATE, TAND, TOR, TINC, TDEC, TADDASSIGN, 
TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN, TCOMMENT, TSPACE, TSUBT, TNOT, TLESS, TGREAT, 
TSPECIAL, TREALNUM};
